### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by ahmad7-glitch** [adityarifqyfauzan/cryptography#1]
![image](https://github.com/user-attachments/assets/e3800077-843b-49aa-95ce-674c3c846d38)
mungkin lebih baik, dikurangi looping pada bagian pengulangan seperti contoh yang ada pada foto tersebut. terima kasih.

**Comment by adityarifqyfauzan** [comment]
Issue ini sepertinya karna terminal ga bisa input string yang terlalu panjang mas🙏
